title: Simple Page
icon: 📝

tabs:
    content:
        columns:
            main:
                width: 2/3
                sections:
                    content:
                        type: fields
                        fields:
                            nav_text:
                                type: text
                                label: Menütext
                            text:
                                type: layout
                                layouts:
                                    - "1/1"
                                    - "1/2, 1/2"
                                    - "1/3, 2/3"
                                    - "2/3, 1/3"
                                    - "7/12, 1/12, 4/12"
                                    - "1/3, 1/3, 1/3"

            sidebar:
                width: 1/3
                sections:
                    pages:
                        type: pages
                        label: Subpages
                    files:
                        type: files
                        label: Files
                    security:
                        type: fields
                        fields:
                            security: fields/kerli81.securedpages.pageconfiguration
    seotab: seo
